### PR TITLE
DSND-2870: Add test coverage and improved logging

### PR DESCRIPTION
**Pull request by cgregoryCH**
* Adds improved structured logging which logs an error when the max retries have been reached.
* Adds unit and integration test coverage.

[DSND-2870](https://companieshouse.atlassian.net/browse/DSND-2870)

[DSND-2870]: https://companieshouse.atlassian.net/browse/DSND-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sthompsonCH — APPROVED** [review]

**Review by kinpang-CH — APPROVED** [review]

**Pull request merged**
